import React from 'react';

function UbaciListu(){

    const listaDesavanja=[
        {
            kategorija:"bioskopi",
            desavanje1:{
                idDesavanja:"/primer1",
                link:"primer1",
                kategorija:"bioskopi",
                slika:"/Slike/evgeni-tcherkasski-972921-unsplash.jpg",
                naslov:"Primer 1",
                opis:"Ovo je opis 1",
                cena:150,
                lokacija:"lokacija 1",
                opisVeliki:"Ovo je veliki opis1",
            },
            desavanje2:{
                idDesavanja:"/primer2",
                link:"primer2",
                kategorija:"bioskopi",
                slika:"/Slike/cristi-tohatan-789483-unsplash.jpg",
                naslov:"Primer 2",
                opis:"Ovo je opis 2",
                cena:100,
                lokacija:"lokacija 2",
                opisVeliki:"Ovo je veliki opis 2",
            },
            desavanje3:{
                idDesavanja:"/primer3",
                link:"primer3",
                slika:"/Slike/david-marcu-1425-unsplash.jpg",
                naslov:"Primer 3",
                kategorija:"bioskopi",
                opis:"Ovo je opis 3",
                cena:200,
                lokacija:"lokacija 3",
                opisVeliki:"Ovo je veliki opis 3",
            }
        },
            {
                kategorija:"festivali",
                desavanje1:{
                    idDesavanja:"/primer4",
                    link:"primer4",
                    slika:"/Slike/greg-rakozy-38800-unsplash.jpg",
                    naslov:"Primer 4",
                    kategorija:"festivali",
                    opis:"Ovo je opis 4",
                    cena:250,
                    lokacija:"lokacija 4",
                    opisVeliki:"Ovo je veliki opis 4",
                },
                desavanje2:{
                    idDesavanja:"/primer5",
                    link:"primer5",
                    slika:"/Slike/jan-szwagrzyk-696393-unsplash.jpg",
                    naslov:"Primer 5",
                    kategorija:"festivali",
                    opis:"Ovo je opis 5",
                    cena:300,
                    lokacija:"lokacija 5",
                    opisVeliki:"Ovo je veliki opis 5",
                },
                desavanje3:{
                    idDesavanja:"/primer6",
                    link:"primer6",
                    slika:"/Slike/finn-hackshaw-400210-unsplash.jpg",
                    naslov:"Primer 6",
                    opis:"Ovo je opis 6",
                    kategorija:"festivali",
                    cena:350,
                    lokacija:"lokacija 6",
                    opisVeliki:"Ovo je veliki opis 6",
                }
            },
            {
                kategorija:"izložbe",
                desavanje1:{
                    idDesavanja:"/primer1",
                    link:"primer1",
                    slika:"/Slike/evgeni-tcherkasski-972921-unsplash.jpg",
                    naslov:"Primer 1",
                    kategorija:"izložbe",
                    opis:"Ovo je opis 1",
                    cena:400,
                    lokacija:"lokacija 7",
                    opisVeliki:"Ovo je veliki opis 7",
                },
                desavanje2:{
                    idDesavanja:"/primer2",
                    link:"primer2",
                    slika:"/Slike/cristi-tohatan-789483-unsplash.jpg",
                    naslov:"Primer 2",
                    kategorija:"izložbe",
                    opis:"Ovo je opis 2",
                    cena:450,
                    lokacija:"lokacija 8",
                    opisVeliki:"Ovo je veliki opis 8",
                },
                desavanje3:{
                    idDesavanja:"/primer3",
                    link:"primer3",
                    slika:"/Slike/david-marcu-1425-unsplash.jpg",
                    naslov:"Primer 3",
                    kategorija:"izložbe",
                    opis:"Ovo je opis 3",
                    cena:500,
                    lokacija:"lokacija 9",
                    opisVeliki:"Ovo je veliki opis 9",
                }
            },
            {
                kategorija:"koncerti",
                desavanje1:{
                    idDesavanja:"/primer1",
                    link:"primer1",
                    slika:"/Slike/evgeni-tcherkasski-972921-unsplash.jpg",
                    naslov:"Primer 1",
                    kategorija:"koncerti",
                    opis:"Ovo je opis 1",
                    cena:550,
                    lokacija:"lokacija 10",
                    opisVeliki:"Ovo je veliki opis 10",
                },
                desavanje2:{
                    idDesavanja:"/primer2",
                    link:"primer2",
                    slika:"/Slike/cristi-tohatan-789483-unsplash.jpg",
                    naslov:"Primer 2",
                    kategorija:"koncerti",
                    opis:"Ovo je opis 2",
                    cena:600,
                    lokacija:"lokacija 11",
                    opisVeliki:"Ovo je veliki opis 11",
                },
                desavanje3:{
                    idDesavanja:"/primer3",
                    link:"primer3",
                    slika:"/Slike/david-marcu-1425-unsplash.jpg",
                    naslov:"Primer 3",
                    kategorija:"koncerti",
                    opis:"Ovo je opis 3",
                    cena:650,
                    lokacija:"lokacija 12",
                    opisVeliki:"Ovo je veliki opis 12",
                }
            },
            {
                kategorija:"pozorišta",
                desavanje1:{
                    idDesavanja:"/primer1",
                    link:"primer1",
                    slika:"/Slike/evgeni-tcherkasski-972921-unsplash.jpg",
                    naslov:"Primer 1",
                    kategorija:"pozorišta",
                    opis:"Ovo je opis 1",
                    cena:700,
                    lokacija:"lokacija 13",
                    opisVeliki:"Ovo je veliki opis 13",
                },
                desavanje2:{
                    idDesavanja:"/primer2",
                    link:"primer2",
                    slika:"/Slike/cristi-tohatan-789483-unsplash.jpg",
                    naslov:"Primer 2",
                    kategorija:"pozorišta",
                    opis:"Ovo je opis 2",
                    cena:750,
                    lokacija:"lokacija 14",
                    opisVeliki:"Ovo je veliki opis 14",
                },
                desavanje3:{
                    idDesavanja:"/primer3",
                    link:"primer3",
                    slika:"/Slike/david-marcu-1425-unsplash.jpg",
                    naslov:"Primer 3",
                    kategorija:"pozorišta",
                    opis:"Ovo je opis 3",
                    cena:800,
                    lokacija:"lokacija 15",
                    opisVeliki:"Ovo je veliki opis 15",
                }
            },
            {
                kategorija:"sportovi",
                desavanje1:{
                    idDesavanja:"/primer1",
                    link:"primer1",
                    slika:"/Slike/evgeni-tcherkasski-972921-unsplash.jpg",
                    naslov:"Primer 1",
                    kategorija:"sportovi",
                    opis:"Ovo je opis 1",
                    cena:850,
                    lokacija:"lokacija 16",
                    opisVeliki:"Ovo je veliki opis 16",
                },
                desavanje2:{
                    idDesavanja:"/primer2",
                    link:"primer2",
                    slika:"/Slike/cristi-tohatan-789483-unsplash.jpg",
                    naslov:"Primer 2",
                    kategorija:"sportovi",
                    opis:"Ovo je opis 2",
                    cena:900,
                    lokacija:"lokacija 17",
                    opisVeliki:"Ovo je veliki opis 17",
                },
                desavanje3:{
                    idDesavanja:"/primer3",
                    link:"primer3",
                    slika:"/Slike/david-marcu-1425-unsplash.jpg",
                    naslov:"Primer 3",
                    kategorija:"sportovi",
                    opis:"Ovo je opis 3",
                    cena:950,
                    lokacija:"lokacija 18",
                    opisVeliki:"Ovo je veliki opis 18",
                }
            }
    ]
    return listaDesavanja;
}

export default UbaciListu;